schema_version: "1.0"
mcp_name: "Croatian Law MCP"
jurisdiction: "HR"

sources:
  - name: "Narodne novine ELI / NN API"
    authority: "Narodne novine d.d."
    official_portal: "https://narodne-novine.nn.hr"
    retrieval_method: "API + HTML_SCRAPE"
    update_frequency: "continuous"
    last_ingested: "2026-02-21"
    license_or_terms:
      type: "government_terms"
      url: "https://narodne-novine.nn.hr/data_access_hr.aspx"
      summary: "Content is publicly accessible for browsing and machine access; usage is subject to Narodne novine terms."
    coverage:
      scope: "Official and international legislation pages with ELI metadata and HTML representations"
      limitations: "This ingestion covers a curated set of 10 statutes relevant to digital regulation and cyber/compliance practice."
    languages:
      - "hr"
      - "en"

data_freshness:
  automated_checks: true
  check_frequency: "weekly"
  last_verified: "2026-02-21"
